global:
  scrape_interval: 15s 

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
        #localhost onde prometheus está rodando
      - targets: ['localhost:9090']

  - job_name: 'gestao-vendas'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
        # ip onde esta rodando aplicação
      - targets: ['000.000.00.000:8080']